adapter:
  mode: rehearsal
  image:
    repository: ghcr.io/jkershawrh/sovereign-ai-201-adapter
    tag: ""
    digest: sha256:9b1eb7bb0c5b6bf2888f02566070b6140d4c6b049c31151bf4eac9a1beba1708
    pullPolicy: IfNotPresent

presentation:
  image:
    repository: ghcr.io/jkershawrh/sovereign-ai-201-presentation
    tag: ""
    digest: sha256:f13a56fb7530c16309098270f3399a8ecc5b59d60481595ea7bd181a7424ca31
    pullPolicy: IfNotPresent
