adapter:
  mode: rehearsal
  image:
    repository: ghcr.io/jkershawrh/sovereign-ai-201-adapter
    tag: ""
    digest: sha256:868e1ced53d28cf07b02007849356b4f1ff78ff17d1d1dd0c2b04fedd6a20f6f
    pullPolicy: IfNotPresent

presentation:
  image:
    repository: ghcr.io/jkershawrh/sovereign-ai-201-presentation
    tag: ""
    digest: sha256:2baef1ba00a221d223f205d8179a8a6cb1ca3113539b6c2e53364c484fe7545a
    pullPolicy: IfNotPresent
